servers = ["home"];
for (i = 0; i < servers.length; i++) {
	thisScan = scan(servers[i]);
	// Loop through results of the scan, and add any new servers
	for (j = 0; j < thisScan.length; j++) {
		// If this server isn't in servers, add it
		if (servers.indexOf(thisScan[j]) === -1) {
			servers.push(thisScan[j]);
		}
	}
}
servers.splice(0, 1)
for (var i = 0; i < servers.length; i++) {
	if(hasRootAccess(servers[i])){
		installBackdoor(servers[i])
	}
}